using KoLiber.Module.Widgets.Models;
using Orchard.ContentManagement.MetaData;
using Orchard.Core.Contents.Extensions;
using Orchard.Data.Migration;
using Orchard.Environment.Extensions;

// This code was generated by Orchardizer
namespace KoLiber.Module.Widgets
{
	[OrchardFeature(Consts.DotpayFeatureID)]
    public class DotpayMigrations : DataMigrationImpl {

        public int Create() {
            ContentDefinitionManager.AlterPartDefinition(nameof(DotpayDonationFormPart), builder => builder
                .Attachable()
                .WithDescription("Allows users to send donations via dotpay.pl")
            );

            SchemaBuilder.CreateTable(nameof(DotpayDonationFormPartRecord), table => table
                .ContentPartRecord()
                .Column<int>(nameof(DotpayDonationFormPartRecord.DotpayId))
                .Column<double>(nameof(DotpayDonationFormPartRecord.SuggestedAmount), col => col.Nullable())
                .Column<string>(nameof(DotpayDonationFormPartRecord.Purpose))
                .Column<string>(nameof(DotpayDonationFormPartRecord.ReturnUrl))
            );

            ContentDefinitionManager.AlterTypeDefinition(Consts.DotpayWidgetName, type => type
                .AsWidget()
                .WithPart(nameof(DotpayDonationFormPart))
            );
            return 1;
        }
    }
}
