using Orchard.ContentManagement.MetaData;
using Orchard.Core.Contents.Extensions;
using Orchard.Data.Migration;
using Orchard.Environment.Extensions;

// This code was generated by Orchardizer
namespace KoLiber.Module.Widgets
{
	[OrchardFeature("KoLiber.Widgets.Dotpay")]
    public class DotpayMigrations : DataMigrationImpl {

        public int Create() {
            ContentDefinitionManager.AlterPartDefinition("DotpayDonationFormPart", builder => builder
                .Attachable()
                .WithDescription("Allows users to send donations via dotpay.pl")
            );

            SchemaBuilder.CreateTable("DotpayDonationFormPartRecord", table => table
                .ContentPartRecord()
                .Column<int>("DotpayId")
                .Column<double>("SuggestedAmount", col => col.Nullable())
                .Column<string>("Purpose")
                .Column<string>("ReturnUrl")
            );

            ContentDefinitionManager.AlterTypeDefinition("DotpayWidget", type => type
                .WithPart("WidgetPart")
                .WithPart("CommonPart")
                .WithPart("DotpayDonationFormPart")
                .WithSetting("Stereotype", "Widget")
            );
            return 1;
        }
    }
}
