using Orchard.ContentManagement.Records;
using Orchard.Environment.Extensions;

// This code was generated by Orchardizer

namespace KoLiber.Module.Widgets.Models {
    [OrchardFeature(Consts.DotpayFeatureID)]
    public class DotpayDonationFormPartRecord : ContentPartRecord {
        public virtual int DotpayId { get; set; }
        public virtual double? SuggestedAmount { get; set; }
        public virtual string Purpose { get; set; }
        public virtual string ReturnUrl { get; set; }
    }
}